### ISSUE TITLE
Magisklist.txt won't restore

### ISSUE THREAD

**Issue by bmcglone5** [adrianmmiller/MagiskHideDenyBackup#1]
Hi @adrianmmiller I'm hoping you can help me with restoring my deny list. I needed to wipe and flash and got the list backup no problem. After flashing, I have my backup list in /sdcard/MagiskList.txt, installed Magisk Manager and enabled zygisk and the deny list, installed the module, rebooted, but I only get a new empty deny list that has overwritten my backup list. I get the export log file that says MagiskList.txt successfully written.

I'm on Magisk 25.2 on stock rooted Pixel 7 Pro. I appreciate your help and the developing the module.

**Comment by adrianmmiller** [comment]
Hi, theres two very distinct modules

MagiskHideDenyBackup: https://github.com/adrianmmiller/MagiskHideDenyBackup

MagiskHideDenyRestore: https://github.com/adrianmmiller/MagiskHideDenyRestore

I fear you have flashed the MagiskHideDenyBackup on both the backing up
part of your process, and then restore one, which would explain the blanked
MagiskList.txt file

There are two separate modules purely to avoid this kind of borkage if i'd made it an 
all in one combined modulesand tried to use various methods to do both, even using 
keycheck some people would get it wrong and blank their MagiskList.txt

The MagiskHideBackup modules script has no code that would blank an
existing MagiskList.txt file, it literally can ONLY copy out the contents
of the MagiskHide or Deny List

Also it pays to always keep a copy of that file off device, whether locally
on a PC or on a cloud drive, for occasions where something goes wrong....

**Comment by adrianmmiller** [comment]
I have edited the README for both modules to make things a LOT clearer, though i did always mention in the first few lines there were 2 modules, some people skim :)

**Comment by bmcglone5** [comment]
Thanks. I totally missed the restore module and now feel like a giant dumbass. I did keep a copy of the deny list. I'm good to go. Thanks again for the help and the awesome tool.

**Comment by adrianmmiller** [comment]
> Thanks. I totally missed the restore module and now feel like a giant dumbass. I did keep a copy of the deny list. I'm good to go. Thanks again for the help and the awesome tool.

hehe we've all done our share of dumb shit with technology...ive been doing it for over 30 years, and some of that in paid professional IT work :) Luckily i never hosed a clients data, unlike MANY IT boffins i know :) I mean ive hosed my own, i once deleted a partition on one of my storage drives full of years of software...an entire 320Gb ...got it all back thanks to TestDisk :)
Thats about the worst thing ive done to myself in 30 years....

as for android and these modules, i ve always said, as these modules and my other android contributions are done in my very time poor periods of life, i half ass something together, often with very rudimntary error checking, test it to the point where it doesnt those something on my gear, and only then do i release it for others (and hope it doesnt hose their devices)

the only time (so far, touch wood) that i saw an issue was with an early version of my GPay SQLite module, where as part of its install it would clear the data for Google Pay (now Wallet) and a kiddie reported that he had lost all the loyalty cards in his Pay app...i'd never used loyalty cards, so that was a leanring experience (it was just annoying for him to have to manually readd them), and i put a keycheck (option to skip) and warning in quickly and made a new release.  There was over 38,000 (probably much higher, i blew away the repo twice) installs of that thing, my 1st module, and so 1 negative install was not a bad result :)

**Comment by adrianmmiller** [comment]
Also i take it you know about these?

https://github.com/adrianmmiller/SuperuserListBackup
https://github.com/adrianmmiller/SuperuserListRestore

Though i really just still allow shit as needed after an install, it was requested by a user of the MagiskHideDeny modules

**Comment by bmcglone5** [comment]
Yeah. I just got my first 3D printer and am experiencing a new world of dumbassery. I've luckily never screwed anything up so bad I could not recover. I don't need the superuser backup, only a few superuser apps. But I deny root to everything that does not explicitly need it. So my deny list is really long. I know I don't need to deny everything, but I'm a little paranoid with my devices and security.

**Comment by adrianmmiller** [comment]
> Yeah. I just got my first 3D printer and am experiencing a new world of dumbassery. I've luckily never screwed anything up so bad I could not recover. I don't need the superuser backup, only a few superuser apps. But I deny root to everything that does not explicitly need it. So my deny list is really long. I know I don't need to deny everything, but I'm a little paranoid with my devices and security.

Its generally recomended to ONLY hide/deny to apps that absolutely need it, over the years weve seen kiddies who come into magisk threads having hidden from every google app to literally every app and wonder why things break. Theres an overhead in every app you hide, and the creator of Magisk warned against overuse of the hide/deny function for this reason

aka less = more better

ive made the point many times by pointing out that me, the creator of the GPay module hasnt had to hide root from Google Pay (now Wallet) for nearly a year....its not even necessary for that anymore...standalone banking apps, yes...and usually in conjunction with HMA: https://github.com/adrianmmiller/Hide-My-Applist-Guide

but dont go nuts...you can actually introduce issues
